### ISSUE TITLE
Referrer policy of child css?

### ISSUE THREAD

**Issue by tungmangtdh3** [w3c/webappsec-referrer-policy#109]
It does not say explicitly about fetching resources from child css. Should we fall back to parent's referrer policy or document's policy if there's undefined poilcy of child (no Referer-Policy header)?
Per definition of empty string policy and referrer policy can be defined "Implicitly, via inheritance", we choose parent's, don't we? 
I am not sure if that is an issue, but I would like to consult author of the specs before I could go through the implementation of Firefox. @jeisinger do you have any advice? Should we say a bit more in the specs?
Thank you very much

**Comment by jeisinger** [comment]
you mean like this case: https://github.com/w3c/web-platform-tests/blob/master/referrer-policy/css-integration/external-import-stylesheet.html ?

If an stylesheet with a non-null location loads a resource, the referrer is the sylesheet's location and the referrer policy is either "default" or whatever the referrer-policy header send with the stylesheet was.

**Comment by tungmangtdh3** [comment]
thanks for the clarification, it's clear to me. I will close this bug.
So, the "Implicitly, via inheritance" indicates only to nested browsing context, right (all other cases like child worker, child css, fall back to default if there's no referrer-policy header in the response)?

**Comment by jeisinger** [comment]
hum, child workers should also inherit from their parent workers. It's just CSS that doesn't have the inheritance concept (as a stylesheet doesn't have a browsing context)
