### ISSUE TITLE
Typo: space between “non-” and “potentially trustworthy”

### ISSUE THREAD

**Issue by j9t** [w3c/webappsec-referrer-policy#118]
Drive-by report: In the live spec at https://www.w3.org/TR/referrer-policy/ there are three, in the document at https://github.com/w3c/webappsec-referrer-policy/blob/master/index.html one occurrence of “non- potentially trustworthy” (the latter being linked). The space should be removed.

**Comment by domfarolino** [comment]
Thanks for filing this @j9t. Seeing as how this is no longer a problem in the living document https://w3c.github.io/webappsec-referrer-policy, I'll go ahead and close this, and the fixes to the typo will appear in the next CR, whenever that may be.

Thanks!
