### ISSUE TITLE
What default policy should new features use?

### ISSUE THREAD

**Issue by jeremyroman** [w3c/webappsec-referrer-policy#121]
This came up in WICG/portals#136. We've generally aimed for portals to lean on the side of exposing less information, but it's also desirable for its behavior to be consistent with how other features behave.

AFAICT, iframe and other subresource fetches all default to the document's referrer policy (which is, by default, `"no-referrer-when-downgrade"` per https://fetch.spec.whatwg.org/#main-fetch.

Would it be recommended for new features to rely on the existing logic (and authors to override the default if they want `"no-referrer"`, `"same-origin"` or similar), or should extra plumbing be added so that new features can have a different global default referrer policy?

@domenic @lucasgadani

**Comment by annevk** [comment]
I think we should allow for more restrictive defaults or have a more restrictive default going forward that new features get to use.

**Comment by fmarier** [comment]
Firefox has been using a [default of `strict-origin-when-cross-origin` in private browsing](https://bugzilla.mozilla.org/show_bug.cgi?id=587523) and this could be a nicer default for new features.

**Comment by domfarolino** [comment]
I think that this can be closed since we've updated the default to strict-origin-when-cross-origin, but Jeremy let me know if there's more discussion you'd like to have.
