### ISSUE TITLE
Inconsistencies with "same-origin" requests

### ISSUE THREAD

**Issue by domfarolino** [w3c/webappsec-referrer-policy#123]
The [origin-when-cross-origin](https://www.w3.org/TR/referrer-policy/#referrer-policy-origin-when-cross-origin) section (and its "strict-" complement) mentions:

> and only the ASCII serialization of the origin of the request client is sent as referrer information when making cross-origin requests from a particular client.

However, the [reference](https://www.w3.org/TR/referrer-policy/#ref-for-referrer-policy-origin-when-cross-origin-5) to "origin-when-cross-origin" (and "strict-") from "determine a request's referrer" returns the origin of the request's [referrer](https://fetch.spec.whatwg.org/#concept-request-referrer), which I believe is not always the same as request's client's origin. I believe they are often the same, however when loading module scripts, the module script baseURL is used as the referrer for its descendants (see [this](https://html.spec.whatwg.org/multipage/webappapis.html#fetching-scripts:internal-module-script-graph-fetching-procedure-2)) even though the descendant and parent share the same fetch client settings object. In this case _I believe_ "referrerOrigin" and request's client's origin are not the same, so the above block quote is misleading. Depending on the intentions of the spec, I see two ways forward:

1. Update the above quote to mention the origin of the referrer will be sent as the referrer for cross-origin requests etc, instead of the request client's origin
2. Modify "determine a request's referrer" to return the request's client's origin instead of `referrerOrigin` in these cases

/cc @yutakahirano @domenic (due to module script involvement)

### Edit:
FWIW going with option (1) will align the spec with the behavior we are trying to achieve with Chrome, and the behavior Firefox currently has (see [this test](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/module/referrer-origin-when-cross-origin.sub.html?label=experimental&label=master&aligned) & [this test](https://wpt.fyi/results/html/semantics/scripting-1/the-script-element/module/referrer-same-origin.sub.html?label=experimental&label=master&aligned)).

**Comment by yutakahirano** [comment]
@mikewest @nyaxt @estark37

**Comment by mikewest** [comment]
It makes sense to me that we'd strip the request's referrer down to an origin, and I expect that the current text just didn't take module scripts' referrer behavior into account. Have other browsers aligned on the same behavior here? If so, we should lock it in with some tests, and change the spec accordingly.

**Comment by jeisinger** [comment]
for CSS stylesheets, we defined a stylesheet loading subresources the behave like it was a client (and thus become the referrer).

I'm wondering why modules are defined to behave differently? That seems rather unfortunate.

We could also change CSS to behave like modules, but afaik that's breaking webcompat

**Comment by domfarolino** [comment]
@jeisinger Could you point me to where this is defined in CSS, and also if there are any tests asserting this behavior? Does this mean that the referrer string and client origin are always same-origin?

Hmm this is interesting, I’m not sure what we should do here then. Would it be best to change one of {CSS subresources, module scripts} to behave like the other, client-wise? If so, I’m wondering if changing module scripts would have implications beyond referrer generation. I’d have to look closer, but @domenic may know.

**Comment by mikewest** [comment]
@domfarolino: https://w3c.github.io/webappsec-referrer-policy/#integration-with-css CSS doesn't do a great job integrating with Fetch. We monkey-patched it.

**Comment by jeisinger** [comment]
As changing CSS would be very painful, I'd rather change module scripts

**Comment by domfarolino** [comment]
Sorry, I think there was some misunderstanding on this thread; it seems like Jochen and I each thought CSS and js modules behaved the opposite, when they actually align referrer-wise. So it sounds like neither has to change, and we can just amend the spec as originally suggested, but let me know if I am missing something.

**Comment by yutakahirano** [comment]
I'm fine with either solutions as long as it is consistent, well specified and well tested.

Another problem: the current spec says the "downgrade" bit is calculated with _environment_ and _request_'s currentURL, but Chrome's implementation calculates it with the referrer string and _request_'s currentURL (see [the code](https://cs.chromium.org/chromium/src/net/url_request/url_request_job.cc?q=computereferrerforpolicy&sq=package:chromium&g=0&l=283)].

> "strict-origin"
>  - If environment is not null:
>    - If environment is TLS-protected and request’s current URL is not a potentially trustworthy URL, then return no referrer.
> - Return referrerOrigin.

@jeisinger, @mikewest, can you help us getting a consensus here? We thought we had one at https://github.com/w3c/webappsec-referrer-policy/issues/123#issuecomment-539369742. Is there any other stakeholders?

**Comment by mikewest** [comment]
@yutakahirano Would you mind putting up a PR against Referrer Policy that we could evaluate?

**Comment by yutakahirano** [comment]
We have two options.

One is keeping the spec and fixing the (Chrome) implementation. No spec work is needed.

Another is to fix the spec - I believe it's something like https://github.com/w3c/webappsec-referrer-policy/pull/129. @domfarolino, do you think it's aligned with Chrome's implementation?

**Comment by domfarolino** [comment]
I've filed a Firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1619285) and created to WPT PRs aligning the tests with the proposal here:
 - https://github.com/web-platform-tests/wpt/pull/22038
 - https://github.com/web-platform-tests/wpt/pull/22039

Would appreciate if @annevk weighed in on this too

**Comment by annevk** [comment]
I'm not sure I fully understand the setup. As far as I can tell these are the actors:

1. Documents that can have a referrer policy.
2. Worklets, module scripts, or style sheets that can have a referrer policy of their own, referenced by the aforementioned documents. (I'll refer to these as style sheets for simplicity below as I think we all want them to behave the same.)
3. "Imported" resources of those style sheets.

Now multiple documents from distinct origins can point to the same style sheet. Does this setup end up leaking that information to the "imported" resources a little bit? I guess so, right, since the document referrer policy serves as a default?

What's the (proposed) interaction between the document referrer policy and that of the style sheet referrer policy, if any?

I'm pretty sure that in Firefox the model has been that the authority is with the style sheet, as far as relaying blame to the "imported" resources goes. It seems this setup would shift that in subtle ways, right?

cc @bzbarsky

**Comment by domfarolino** [comment]
> What's the (proposed) interaction between the document referrer policy and that of the style sheet referrer policy, if any?

This isn't so much focused on referrer policy as it is the referrer string. If A.com fetches a style sheet B.com/style.css, which in turn fetches a descendant A.com/sub_style.css, and the referrer policy for all of these requests is "same-origin": what should the `Referer` be for the request A.com/sub_style.css? In other words, is this request considered same-origin, or cross-origin?

I believe the spec considers this to be a same-origin request, as per [this definition](https://w3c.github.io/webappsec-referrer-policy/#same-origin-request). The spec compares the request's URL with the request's origin (which would be the document's origin, `A.com`). I think It should be comparing the request's URL with its referrer string's origin (origin = `B.com`), and consider it a cross-origin request (relative to the parent style sheet), as far as referrer calculation goes. Does that make sense?

**Comment by annevk** [comment]
From the perspective of the authority being with the style sheet (which is on B.com) it seems weird for the request origin to be A.com. But then I guess service workers flipped that to some extent already.

It's not entirely clear to me that using the computed referrer as a basis for origin comparisons is sound however, but the general idea makes sense to me. I'm curious what happens for more involved scenarios with redirects and such.

**Comment by domfarolino** [comment]
> From the perspective of the authority being with the style sheet (which is on B.com) it seems weird for the request origin to be A.com. But then I guess service workers flipped that to some extent already.

I agree; it's weird because it lets this spec compute "same-origin-ness" in a different way than other parts of the platform might. But it would also feel weird if, as you said, the "authority" is with the style sheet (whose URL is the descendant's referrer string), and we don't consult the referrer string (from the "authority") when determining if it should be stripped.

> I'm curious what happens for more involved scenarios with redirects and such.

The referrer string for descendants will be whatever the parent module script/style sheet's URL is I believe, even after redirects, right? Perhaps I'm missing some of the more interesting scenarios? If a redirect (for e.g., a module script or style sheet) is served with a new referrer policy, I know Fetch at least handles that in step 14 https://fetch.spec.whatwg.org/#http-redirect-fetch.

**Comment by annevk** [comment]
I meant redirects on the resources loaded from the style sheet. (And I was worried about cases where the style sheet does not have an obvious referrer, e.g., if it's a `data:` URL, but couldn't construct something interesting.)

**Comment by domenic** [comment]
(FWIW: the proposed change makes sense to me at a high level, but I haven't dug into the details or performed any review, as it seems @annevk is doing so, and I'll wait for that discussion to be settled first. Please let me know if it'd be better for me to get involved now.)

**Comment by bzbarsky** [comment]
I'm still trying to make sense of all the comments in this bug, but I think the high-level point is that the referrer and the referrer policy should come from the same place, generally.  For stylesheet subresources, if we use the sheet as the referrer (which imo we should) we should also use its referrer policy (which maybe it can inherit from the document if it doesn't specify its own).

And when redacting the referrer for to do "origin-when-cross-origin" we should not change the referrer source, and should do the same-origin checks against that source, imo.

**Comment by domfarolino** [comment]
Correct. Basically when redacting the referrer for `same-origin` or `origin-when-cross-origin` policies, how should we determine if the request is cross-origin? By comparing the request's origin with the request's URL's origin? Or by comparing the request's referrer's origin with the request's URL's origin? They're not always the same.

I think we should do the latter, but the referrer policy spec does the former.

**Comment by domfarolino** [comment]
And FWIW [this test](http://wptpr.live/22038/html/semantics/scripting-1/the-script-element/module/referrer-same-origin.sub.html) (from [this pr](https://github.com/web-platform-tests/wpt/pull/22038)) indicates that Firefox compares a request's origin with the request's URL's origin, which is why I filed the FF bug.

Here's a WebKit bug as well: https://bugs.webkit.org/show_bug.cgi?id=208681

**Comment by bzbarsky** [comment]
I sort of feel like the most sensible thing to do is to do the origin compare between the origin that will have its information exposed (i.e. the request's referrer's origin) and the URL origin....

**Comment by domfarolino** [comment]
I agree. Thanks for weighing in on this lengthy thread. We might benefit from more tests (i.e., for redirects cases Anne has mentioned), but otherwise I think we can move forward with the PR.
