### ISSUE TITLE
[proposal] no-referrer-when-crossorigin

### ISSUE THREAD

**Issue by Jxck** [w3c/webappsec-referrer-policy#136]
In company intra service, no referrer outside intra but full path inside service are so reasonable behavior.
in current policies, it need to use no-referrer but its too strict.
use strict-origin-when-crossorigin will send origin, it omits path value but origin has enought entropy in some case.

for example. imagine one hacker writes blog article about detail of some valunability on their blog. 
and gathering referer value in access_log.
values like below are meaningful for OSINT.

- https://bugs.${product}.{company}.com
- https://blog.${company}.com
- https://wiki.${project}.com

other scenario. a company has a new project called *orange* which is not announced public yet. they has intra site like below.

- https://orange.${company}.com
- https://git.orange.${company}.com
- https://orange\.dev

referrer leaks about project orange exists.

so policy like below works fine in intra requirement.
- same https origin -> fullpath
- other -> no-referrer

this could apply company intra wide, for protect confidential information to leak.

**Comment by domfarolino** [comment]
Doesn't the `same-origin` policy cover this?

**Comment by Jxck** [comment]
@domfarolino IIUC same-origin sends for downgrade too. so same-origin + no-downgrade seems fit(policy naming rule is difficult for me), does it covered by other policy?

**Comment by domfarolino** [comment]
The same-origin policy shouldn’t send anything if the origins aren’t the same. See this definition, which shows that “scheme” is part of an origin, therefore downgrade requests should be considered cross-origin: https://html.spec.whatwg.org/multipage/origin.html#same-origin

**Comment by Jxck** [comment]
oh I mis using downgrade. I meant to no http:// to http://. only send in https:// to https://.

**Comment by annevk** [comment]
`same-origin` does indeed seem to cover this use case. It's effectively no-referrer when cross-origin, which OP's scenarios would need.

**Comment by domfarolino** [comment]
> I meant to no http:// to http://. only send in https:// to https://.

Yeah, same-origin won’t send on requests that are http => http where the rest of the origin is different. The one that that the same-origin policy does not cover is _still_ sending on https => https where the rest of the origin diff re, but I don’t think there’s a use in that.

**Comment by Jxck** [comment]
I got it, thanks guys.
