### ISSUE TITLE
Strip url check for null url appears redundant

### ISSUE THREAD

**Issue by gterzian** [w3c/webappsec-referrer-policy#139]
At Step 1 of https://w3c.github.io/webappsec-referrer-policy/#strip-url, there is a check for `url` being `null`, however `url` seems to always be non-null at the various call sites. 

Should we remove this step 1?

**Comment by domfarolino** [comment]
This seems reasonable, but I'd like to get some more eyes on it too. @estark37 ?

**Comment by domfarolino** [comment]
Closed by https://github.com/w3c/webappsec-referrer-policy/commit/4620a935b1d103753ca421833e9d69a392884853.
