### ISSUE TITLE
"Strip url for use as a referrer" sets path to null, which is a spec type error

### ISSUE THREAD

**Issue by gsnedders** [w3c/webappsec-referrer-policy#153]
c.f. https://w3c.github.io/webappsec-referrer-policy/#strip-url and https://url.spec.whatwg.org/#concept-url-path

Notably, Referrer Policy says:

> Set url’s path to null.

But URL says:

> A URL’s path is a list of zero or more ASCII strings, usually identifying a location in hierarchical form. It is initially empty.

(i.e., doesn't permit null as a value)

Looking at http://wpt.live/referrer-policy/4K+1/gen/top.meta/same-origin/xhr.http.html, it appears that Chrome uses `[""]` (resulting in `http://wpt.live/`) and Safari uses `[]` (resulting in `http://wpt.live`). Firefox seems to just use no-referrer in this case.

**Comment by annevk** [comment]
It should be set to « the empty string » (to match the type of the spec). HTTP(S) URLs always have a path.
