### ISSUE TITLE
Question in relation to Referrer-Policy header and its relation with link rel attribute

### ISSUE THREAD

**Issue by evilaliv3** [w3c/webappsec-referrer-policy#159]
Hello,

i've  doubt about relation to ```Referrer-Policy``` header and its relation with link rel attribute that i could not find described in any spec and i would welcome your clarification.

Supposing 1: setting the ```rel``` property of an HTML link <a> to the value ```noreferrer``` is equivalent to set the same attribute to ```noreferrer noopener``` (because ```noreferrer``` implies ```noopener``` as stated explicitly stated in the [specs](https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer)

Supposing 2: setting the HTTP ```Referrer-Policy``` header to the value ```no-referrer``` is equivalent to set the ```rel``` property of any HTML link served within the request to the value ```noopener```(is this statement correct?)

Is it correct to expect that setting the  HTTP ```Referrer-Policy``` header would obtain exactly same result of setting the ```rel``` any HTML link served within the request to the value ```noreferrer noopener ```

Thank you!

**Comment by hackademix** [comment]
> Supposing 2: setting the HTTP `Referrer-Policy` header to the value `no-referrer` is equivalent to set the `rel` property of any HTML link served within the request to the value `noopener`(is this statement correct?)

No

> Is it correct to expect that setting the HTTP `Referrer-Policy` header would obtain exactly same result of setting the `rel` any HTML link served within the request to the value `noreferrer noopener `

No it's not, because as you said no relationship between the HTTP `Referrer-Policy` header and the window.opener value in the target browsing context is stated anywhere by the specs.

However, depending on your use case, this might not be a big deal, since [any link with target="_blank" defaults to noopener](https://html.spec.whatwg.org/multipage/links.html#following-hyperlinks).

**Comment by annevk** [comment]
They are related in that `rel=noreferrer` takes precedence, but that's about it. You might want to look at `Cross-Origin-Opener-Policy`.

**Comment by evilaliv3** [comment]
Thank you @annevk, this advice is really helpful. I just looked at your suggestion and we are going to immediately implement it.
