### ISSUE TITLE
null -> "the empty string"

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-referrer-policy#21]
Would it be possible to make the default referrer policy (i.e., the lack of one) represented by the empty string value? That is how it's represented in Fetch https://fetch.spec.whatwg.org/#referrerpolicy. E.g., when a `Request` arrives in a service worker. It seems simpler if all policies are part of an enum, as there doesn't seem to be a need to vary on types here unless I'm missing something.

See https://github.com/whatwg/fetch/issues/226 for context.

**Comment by estark37** [comment]
That seems reasonable to me. @jeisinger?

**Comment by jeisinger** [comment]
yep, sounds reasonable.

maybe we can do that change and then mark the current editor's draft as a new working draft?
