### ISSUE TITLE
Feature request: Disown window.opener 

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec-referrer-policy#23]
This is to re-raise this issue in the context of the new Referrer-Policy spec with it's own header.

https://github.com/w3c/webappsec/issues/139

It would be nice to have a no-window-opener or similar flag for Referrer-Policy.  It does change the spec quite a bit to allow multiple tokens as we probably don't want to add another value to the policy enum for every current policy to imply this.

Is it better that this stay as a CSP directive?

**Comment by annevk** [comment]
We have just decoupled this in HTML by introducing rel=noopener (though there's still some details to be figured out, see https://github.com/whatwg/html/pull/323). Let's not couple them again.

**Comment by hillbrad** [comment]
Awesome, thanks.  I missed that thread.
