### ISSUE TITLE
Dynamically inserted \<meta name="referrer"\> may slow down speculative loadings

### ISSUE THREAD

**Issue by tzik** [w3c/webappsec-referrer-policy#25]
The speculative resource loading of Blink conflicts to a dynamically inserted \<meta name="Referrer"\>.
Blink scans HTML source to collect URLs for speculative loading as soon as the HTML arrived. In this phase, it skips all \<script\>.
However, since the \<script\> may insert \<meta\> to override the referrer policy, and the UA has to respect it, the UA cannot start loading the collected URLs until the script execution completes.

I.e, the UA can't start loading "foo.png" below speculatively until the preceding \<script\> ran.
\<!doctype html\>
\<script\>document.write('\<meta name="Referrer" content="none"\>')\</script\>
\<img src="foo.png"\>

@yutakahirano, @nyaxt.

**Comment by annevk** [comment]
There's two solutions here: 1) no preloading 2) dynamic meta element insertion has no guarantees. I think we should go with 2.

**Comment by franziskuskiefer** [comment]
Firefox currently drops cached images if the referrer policy changes, which is sub-optimal to say the least. I'd prefer something like @annevk solution 2, i.e. re-use any cached load even if the referrer policy might be a different one when it comes to the actual load.

**Comment by jeisinger** [comment]
it's 2) essentially. I hoped that the "Note: implementors are advised to also respect..." would clarify that it's not a must.
