### ISSUE TITLE
Add appropriate [CEReactions] annotation

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-referrer-policy#27]
After https://github.com/whatwg/html/pull/1069 lands, all `referrerPolicy` attributes will need to be updated with `[CEReactions]`.

Also, while I'm here: why not define these in a single mixin, and then do `HTMLWhateverElement implements ReferrerPolicyUtils` 5 times?

---

Alternately we're happy to upstream the HTML-ey parts of this to HTML, assuming it has cross-vendor interest. I think it's OK either way though.

**Comment by domenic** [comment]
It looks like similar to https://github.com/w3c/webappsec-subresource-integrity/issues/31 the best way might be to integrate this into HTML directly. That is:

- HTML defines the `referrerpolicy=""` content attributes and `referrerPolicy` IDL attributes
- We upstream the monkeypatches in "Nested Browsing Contexts", "Workers", and "Integration with HTML"
- Maaaybe we move the hand-wavey "If request was initiated by an element with a referrerpolicy content attribute..." to something more formal, where we pull off the content attribute at the appropriate times and thread it through the fetching algorithms appropriately. We could leave that for later though.

If this plan sounds good, then I'm happy to help with it. Let me know and I can get started on a pull request to HTML that you can review, after which the monkeypatches can be removed.

**Comment by jeisinger** [comment]
if you could help, that'd be great!
