### ISSUE TITLE
Use of "active document" in determining the referrer looks wrong

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-referrer-policy#29]
https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer step 3 substep 3 subsubstep 1 says:

>  Let document be the Document object of the active document of the browsing context of environment’s responsible browsing context. 

What this means is that if a load happens in a document that's _not_ active, the referrer will be set to whatever document is active in the same browsing context, which has nothing whatsoever to do with where the load is happening.  I'm not sure what this bit is trying to do by using "active document", but this doesn't seem right.

**Comment by domenic** [comment]
After #58 this has been slightly rejiggered so that the relevant text is now

> Let _document_ be the `Document` object of the active document of the browsing context of _environment_’s responsible browsing context. 

It sounds like the correct fix here is to use _environment_'s global object's associated Document? (_environment_'s global object is guaranteed to be a Window in this step).
