### ISSUE TITLE
Define referrerPolicy IDL attribute

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-referrer-policy#3]
It seems only the content attribute is defined. We should also define the corresponding IDL attribute (and the elements that implement it). It should be limited to known values and it should have an uppercase "P" to remain consistent with HTML naming conventions.

**Comment by sc0ttbeardsley** [comment]
@annevk where should this be defined? Here? https://fetch.spec.whatwg.org/#referrerpolicy

**Comment by annevk** [comment]
It should be defined together with the content attribute.

You want to have something similar to https://w3c.github.io/webappsec-subresource-integrity/#element-interface-extensions except I see now that the language used there to define the IDL attributes is wrong. (The IDL is correct however, you want to use that as an example.)

The language you want is:

> The `referrerPolicy` IDL attribute must [reflect](https://html.spec.whatwg.org/multipage/infrastructure.html#reflect) the `referrerpolicy` content attribute, [limited to only known values](https://html.spec.whatwg.org/multipage/infrastructure.html#limited-to-only-known-values).

**Comment by annevk** [comment]
(The alternative here is to instead patch HTML and define the attribute there. That is what we want to do in the long run I think. So the HTML vocabulaire remains self-contained.)

**Comment by jeisinger** [comment]
@estark37

**Comment by hsivonen** [comment]
Do the editors agree that the IDL attribute should exist as proposed by @annevk in *some* relevant spec? That is, can we implement it in Gecko and not have to bikeshed its existence or name later?

**Comment by jeisinger** [comment]
@hsivonen, yes - adding to the referrer policy spec
