### ISSUE TITLE
Please work with the HTML spec to not monkeypatch browsing context creation

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-referrer-policy#30]
https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-implicit-nested is inserting steps into browsing context creation that are not at all obvious while reading the HTML spec that defines creation of browsing contexts.  This should probably be integrated better with HTML (e.g. via an explicit hook HTML invokes).

@annevk, thoughts?

**Comment by bzbarsky** [comment]
Oh, and probably similar for workers....

**Comment by annevk** [comment]
HTML itself could also use some refactoring in this area since many things inherit into about:blank / srcdoc and none of that is really clear. At least not to me.

**Comment by mikewest** [comment]
I agree entirely. See also https://github.com/w3c/webappsec-subresource-integrity/issues/31 for a similar discussion.

/cc @estark37 @jeisinger

**Comment by domenic** [comment]
I was going to do some of the work here as discussed in https://github.com/w3c/webappsec-referrer-policy/issues/27#issuecomment-212544943.
