### ISSUE TITLE
Srcdoc referrer policies don't interact well with <meta referrer>

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-referrer-policy#31]
The way the spec is written right now, a srcdoc iframe snapshots its owner document's referrer policy at the point when it creates its browsing context.  If that parent document's referrer policy then changes due to a `<meta referrer>`, the srcdoc's referrer policy will NOT change.  Is that the desired behavior?

**Comment by estark37** [comment]
I think this is desired behavior and was resolved in https://github.com/whatwg/html/pull/1205, is that correct? (@domenic)

**Comment by domenic** [comment]
Right, I think we concluded that, with some of the extra formalization performed in https://github.com/whatwg/html/pull/1205, the behavior described here is the desired one.

**Comment by bzbarsky** [comment]
Why is that the desired behavior?  The referrer is dynamically grabbed from the container document, but the referrer policy is snapshotted?  Seems to me they should both be snapshots or both be dynamic.

**Comment by domenic** [comment]
Hmm, where is the referrer grabbed dynamically from the container document?

> The document's referrer is a string (representing a URL) that can be set when the Document is created.

- https://html.spec.whatwg.org/#initialise-the-document-object set them together (steps 7 and 9) 
- https://html.spec.whatwg.org/#creating-a-new-browsing-context set them together (steps 9 and 10)

**Comment by bzbarsky** [comment]
https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer step 3 substep 3 subsubsteps 2 and 3.

**Comment by bzbarsky** [comment]
And note that https://html.spec.whatwg.org/#initialise-the-document-object does not set the referrer for srcdoc documents, because in step 9 the "If resource is a request" precondition is false: a srcdoc has a response but not a request.  See https://html.spec.whatwg.org/#process-the-iframe-attributes

So for srcdoc documents the "document's referrer" is never set right now per spec, as far as I can tell.  Luckily, https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer never tries to use it for a srcdoc document.

**Comment by domenic** [comment]
I see, you were talking about the referrer/referrer policy at fetching time, not document creation time. So about the referrer of requests initiated inside that document, not about `document.referrer`.

After thinking about this a bit more, I appreciate the asymmetry you are referring to. Roughly, when performing a request from "inside" an iframe srcdoc document:

- We determine the referrer by saying "oh, the URL is meaningless (it's about:srcdoc); let's look up to the parent".
- We *should* determinine the referrer policy by saying "oh, the referrer policy is unset; let's look up to the parent".

> https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer step 3 substep 3 subsubsteps 2 and 3.

Hmm. These just seem wrong. For example it doesn't recursively climb.

I'll send a couple of PRs here to straighten this out.

**Comment by domenic** [comment]
I gave this a shot but without #40 straightened out it's pretty hard.

The essential asymmetry is that referrer is computed "lazily" by using the value "client" by default; then "Determine request's referrer" takes over and gets a chance to climb iframe srcdocs and such. Whereas, referrer policy does not have this model: the request has a referrer policy, and if it's the default of "", then we don't know if that's because the request initiated from an iframe srcdoc document, or because it came from a normal document with no referrer policy set.

I'm not sure how to best to deal with this.

**Comment by domenic** [comment]
Oh, wait. Fetch already does this kind of lazy climbing for us, kind of:

> If request's referrer policy is the empty string and request's client is non-null, then set request's referrer policy to request's client's associated referrer policy. [REFERRER]

We just need to make sure that works correctly for iframe srcdoc documents. Got it, HTML PR incoming.

**Comment by bzbarsky** [comment]
> So about the referrer of requests initiated inside that document, not about document.referrer

Yes!  Sorry for the confusion there.

**Comment by estark37** [comment]
I believe this is fixed by https://github.com/whatwg/html/commit/5d7c532fc9aa275bd3b12d469b9841c0bad4f50d (@domenic please correct me if Im wrong!)
