### ISSUE TITLE
Should the referrerPolicy attribute be part of the "relevant mutations" for HTMLImageElement?

### ISSUE THREAD

**Issue by jdm** [w3c/webappsec-referrer-policy#33]
https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations defines a set of mutations that cause the image element to request the image data. There's no text in this specification that indicates how modifications to the `referrerPolicy` attribute are supposed to affect `<img>` after a load has previously been started (whether it has previously completed or not).

**Comment by annevk** [comment]
I don't think it should. It's already too late by then (to avoid leaking) and although it can, it generally will not result in a different resource.
