### ISSUE TITLE
Consider being less draconian in conflict resolution

### ISSUE THREAD

**Issue by jeisinger** [w3c/webappsec-referrer-policy#4]
Currently, setting an unknown referrer policy, or an conflicting referrer policy results in setting the policy to "never".

At the last phone-call it was suggested to be less draconian, but I don't remember the details.

@estark37 @mikewest

**Comment by mikewest** [comment]
@devd suggested that deploying new policy keywords is difficult to do in a backwards-compatible way, and that it would be simpler if we allowed the policy to be overwritten by the last-delivered header. That makes sense to me, and matches what we do for `<meta>` delivery.

**Comment by estark37** [comment]
Isn't this what the spec already says? I see https://w3c.github.io/webappsec-referrer-policy/#set-referrer-policy that seems to describe the less-draconian version, and I don't see anywhere describing the draconian version.

**Comment by estark37** [comment]
Oh wait, now I see that https://w3c.github.io/webappsec-referrer-policy/#determine-policy-for-token returns No Referrer for an unknown value.

Though it does still seem to me that conflicting valid values would result in the latest header taking precedence, according to the current spec.

**Comment by devd** [comment]
Unfortunately, an older browser will see a new keyword as invalid and fall
back to none.

**Comment by estark37** [comment]
I think this can be closed now; let me know if there's more work to do here.

**Comment by jeisinger** [comment]
can you send a patch for blink?

**Comment by estark37** [comment]
Yep, will do

**Comment by estark37** [comment]
https://codereview.chromium.org/1454823004/

**Comment by estark37** [comment]
oops didn't mean to reopen
