### ISSUE TITLE
HTML integration plan

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-referrer-policy#43]
I got started on HTML integration in https://github.com/whatwg/html/pull/1153 and https://github.com/w3c/webappsec-referrer-policy/pull/42, but there is still much to do. Here are the issues I see:

- [x] HTML's definition of "environment settings object" should explicitly get a "referrer policy" field, instead of having it be patched in in "Core concepts" (https://github.com/whatwg/html/pull/1205)
- [x] The monkeypatch in "Integration with HTML", regarding creating Documents or WorkerGlobalScopes, should be integrated into HTML (https://github.com/whatwg/html/pull/1205)
- [x] The monkeypatches in "Implicit delivery" should be integrated into HTML (https://github.com/whatwg/html/pull/1205)
- [x] HTML has removed "API referrer source" in the course of Fetch integration. @annevk, how should this be changed?
- [x] All places where the `referrerpolicy` content attribute applies should explicitly pass along the referrer policy when making the appropriate fetch (#40), similar to what is done with the `crossorigin` content attribute today.

**Comment by annevk** [comment]
"API referrer source" is now basically the environment settings object itself rather than a field on it, passed to fetch as request's client. (Or you can set an explicit referrer through request's referrer.)

**Comment by domenic** [comment]
@annevk with that in mind do you have a suggestion for how to fix https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer step 3.3.2? It doesn't seem obvious to me.

**Comment by annevk** [comment]
I think for a worker you'd just inspect the worker itself for the referrer policy. That would be analogous to CSP. What it states now seems wrong, but I might be missing something?

**Comment by domenic** [comment]
I was hoping for some explicit text, or a pull request on top of my #42 :)

**Comment by estark37** [comment]
@domenic did you happen to already have a plan for fixing the "API referrer source" reference in https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer? I wonder if it should be the creation URL of the environment settings object...

**Comment by domenic** [comment]
I don't have a plan; I was hoping @annevk would give more concrete suggestions. But maybe this isn't so bad after all...

> I wonder if it should be the creation URL of the environment settings object...

I believe that is correct, for the worker case. For the document case, the current text seems correct, although I'm not sure on the difference between the responsible browsing context's active document, and the responsible document.

The algorithm looks like it could be cleaned up a decent bit. Here is my draft to replace the current step 3:

1. If request's referrer is a URL, then let referrerSource be request's referrer.
1. Otherwise,
  1. If environment's global object is a Window object, then
    1. Let document be the active document of environment's responsible browsing context.
    1. If document's origin is an opaque origin, return no referrer and abort this algorithm.
    1. While document is an iframe srcdoc document, let document be document's browsing context's browsing context container's Document.
    1. Let referrerSource be document's URL.
  1. Otherwise, let referrerSource be environment's creation URL.

**Comment by domenic** [comment]
In a series of wonderful pull requests (https://github.com/whatwg/html/pull/1641 https://github.com/whatwg/html/pull/1649 https://github.com/whatwg/html/pull/1651) @estark37 finished this off!
