### ISSUE TITLE
Clarify priority of Referrer Policy Delivery

### ISSUE THREAD

**Issue by tungmangtdh3** [w3c/webappsec-referrer-policy#48]
Specs said "when multiple sources specify a referrer policy, the value of the latest one will be used. This makes it possible to deploy new policy values" in [1] but I am confusing about priority of that.
There's a case for example:

(a) What if the document ships a referrer Policy and the worker (called from doc) ships with/without a new referrer policy?

If we have multiple sources define referrer policy, anyway do we know which one is latest one?
I don't know if this should be considered an issue or question. Do we have question channel of this specs?
Could you advise? @annevk @jeisinger
Thanks so much.
[1] https://w3c.github.io/webappsec-referrer-policy/#unknown-policy-values

**Comment by jeisinger** [comment]
it's supposed to say that if you do

var a = document.createElement('a');
a.referrerPolicy = 'origin'; // safe fallback
a.referrerPolicy = 'fancy-new-thing';

and 'fancy-new-thing' isn't implemented, we'll keep using 'origin'

**Comment by tungmangtdh3** [comment]
Thanks you.
I am more concerned about priority of Referrer Policy delivering in [1] (public version)
Question is 
(a) What if the document ships a CSP with a referrer Policy and the worker (called from the document) ships a CSP with a different referrer policy?

(b) Same as (a) but the main document uses <meta referrer=""> but the worker ships with a different referrer policy delivered through CSP. What should be the expected behavior?

(c) What about sub workers? If a main document ships a referrer policy, the workers ships it's own referrer policy through CSP, which one applies to the sub worker? The main document's? The worker's?

[1] https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery

These questions are based on public version. I see CSP is not mentioned anymore in newest draft version, but it may have similar priority concern.
Could you clarify that?

**Comment by jeisinger** [comment]
(note that delivery via CSP doesn't exist anymore in the latest draft, but it's a dedicated header now)

in a) the CSP of the worker is applied to the worker

I don't get b)

in c) if the sub-worker doesn't have a CSP it would inherit the policy of the worker that spawned it

**Comment by tungmangtdh3** [comment]
b) is the mostly the same with a)
Yay! Thank so much for your clarification
Close it for now

**Comment by domenic** [comment]
This is related to #46.

> and 'fancy-new-thing' isn't implemented, we'll keep using 'origin'

This isn't how things are currently specced or implemented. The spec follows the same logic as "CORS setting attributes" and other enumerated attributes (like `<input type>` or `<track kind>`), where setting to an invalid type falls back to the "invalid value default".

See http://jsbin.com/wehogulohu/edit?html,console,output for a CORS test.  https://jsbin.com/tijoxe/edit?html,console,output is a referrer policy test, using the nonstandard chrome `referrerpolicy` (all lowercase) property; it shows how it falls back to the `""` property, which makes sense given the Chrome source code:

```
[Reflect, ReflectOnly=("","no-referrer","origin","no-referrer-when-downgrade","origin-when-cross-origin","unsafe-url"), ReflectMissing="", ReflectInvalid=""] attribute DOMString referrerpolicy;
```

**Comment by jeisinger** [comment]
Well, then that's a bug

Domenic Denicola <notifications@github.com> schrieb am Fr., 6. Mai 2016,
16:47:

**Comment by domenic** [comment]
Hmm. We should figure out how to spec that then. Can you think of any other IDL attribute on the web platform that works that way? Can you figure out a way to reconcile the mismatch between the semantics you want for IDL attributes and the semantics for content attributes, which don't retain a "memory" of their old value?

**Comment by estark37** [comment]
@jeisinger I don't think we need it to work that way; I think it would only be a convenience, because you could always use feature detection:

```
var a = document.createElement('a');
a.referrerPolicy = 'fancy-new-thing';
if (a.referrerPolicy == "")
  a.referrerPolicy = 'origin'; // safe fallback
```

(Unlike the header, where you can't do feature detection before deciding which value to send in the header.)

**Comment by jeisinger** [comment]
Fair enough. I think the initial text is from when we didn't have feature
detection and you only could blindly thirties l throw things at the meta tag

Emily Stark <notifications@github.com> schrieb am Fr., 6. Mai 2016, 18:47:

**Comment by jeisinger** [comment]
I guess my phone is thirsty or something...

Jochen Eisinger <jochen@chromium.org> schrieb am Fr., 6. Mai 2016, 18:48:

**Comment by estark37** [comment]
Hahah that was an excellently nonsensical autocorrect. Anyway yeah I have https://github.com/w3c/webappsec-referrer-policy/issues/46 open to clarify that the fallback behavior applies to the header, not the attribute.

**Comment by tungmangtdh3** [comment]
Close it, thanks all for helping me
