### ISSUE TITLE
Add the non-downgrading versions of origin and origin-when-cross-origin

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec-referrer-policy#50]
As discussed [on the list](https://lists.w3.org/Archives/Public/public-webappsec/2016Mar/0085.html), in the [last teleconf](https://www.w3.org/2016/04/20-webappsec-minutes.html#item09) and in the Face-to-face, I will follow up #19 with spec changes for the other two proposed policy states.

**Comment by fmarier** [comment]
As [mentioned](https://github.com/w3c/webappsec-referrer-policy/pull/19#issuecomment-220077209) in #19, once these new states are in, both Fetch and HTML will need to be updated too.

**Comment by fmarier** [comment]
And the [Security Considerations](https://github.com/w3c/webappsec-referrer-policy/blob/0f9d26e8702faf8130f62fdc7afc004ce2ee7a16/index.src.html#L900-L923) should probably mention the new states too.

**Comment by fmarier** [comment]
The [web platform tests](https://github.com/w3c/web-platform-tests/tree/master/referrer-policy) will also need to be updated for the three new states (the third one being `same-origin` which has already been merged into the spec).

**Comment by fmarier** [comment]
Reopening since I still need to update:

- Fetch
- HTML
- Web Platform tests

**Comment by fmarier** [comment]
HTML changes here: https://github.com/whatwg/html/pull/1589

**Comment by annevk** [comment]
(Updated your comment to point to the Fetch and WPT issues.)

**Comment by fmarier** [comment]
The tests are done.
