### ISSUE TITLE
What is the motivation for "legacy keywords" in the header?

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-referrer-policy#53]
Why does the Referrer-Policy header allow "never", "default", and "always"?

I was under the impression it was because there were shipping implementations that allowed them. However, https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Umj9iVRJM70 indicates that nobody has implemented the header yet, with Blink being the first.

At this point my best guess is that a few user agents have already shipped `<meta name="referrer">`, which allows the legacy keywords, and that the desire is that the Referrer-Policy header be consistent with the `<meta>` element?

I don't think that's a very strong argument. Mainly because we're using `<meta name="referrer">`, not `<meta http-equiv="Referrer-Policy">`, so there is no reason to say that the meta element should be consistent with the HTTP header.

As such, it seems better to me to say that the HTTP header matches the `referrerpolicy=""` content attribute in disallowing the legacy values, instead of saying it must match `<meta>` in allowing them.

**Comment by estark37** [comment]
I buy your argument that it shouldn't support the legacy keywords, but I don't see that it actually does. Where are you looking? I'm looking at https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header which doesn't list "never" or "default" or "always" in the policy-token values.

**Comment by estark37** [comment]
By the way, @fmarier, can you confirm that Firefox hasn't implemented the Referrer-Policy header yet? I wasn't 100% sure if you had or not.

**Comment by fmarier** [comment]
> can you confirm that Firefox hasn't implemented the Referrer-Policy header yet?

Correct, we haven't implemented it yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1264164

**Comment by estark37** [comment]
Doh, don't know how I failed to find that in my bug search, thanks @fmarier!

**Comment by domenic** [comment]
Well, https://w3c.github.io/webappsec-referrer-policy/#parse-referrer-policy-from-header links to https://w3c.github.io/webappsec-referrer-policy/#determine-policy-for-token which processes the legacy keywords. I'm not sure what the grammar production is used for...

**Comment by estark37** [comment]
Ahh, ok, I see, you're right!

**Comment by estark37** [comment]
I think that determine-policy-for-token is only used for Referrer-Policy headers, so perhaps we can just delete the legacy keywords from that algorithm. (And maybe just delete the grammar too.)

**Comment by annevk** [comment]
That algorithm is needed to support `<meta name=referrer>` in HTML. I think that is the only place that needs to support legacy values. Everything else can use the ordinary "referrer policy" definition.

**Comment by domenic** [comment]
We could also move the legacy value translation into HTML, so that we perform the translation before even calling into the referrer policy spec. That seems a bit nicer to me. Then the algorithm can be deleted.

(I'd like to do that separately from https://github.com/whatwg/html/pull/1694 though.)

**Comment by estark37** [comment]
I like the idea of doing the legacy values in HTML.

If we delete "Determine token's Policy", I'm not sure how "Parse a referrer policy from a Referrer-Policy header" should look -- i.e. how to translate from the `token` in the header to a referrer policy. Can I simply say: "For each `token`, if `token` is a referrer policy, set `policy` to `token`"?

**Comment by domenic** [comment]
That sounds right to me. (Also excluding the empty string, which I guess could only happen if you also accept the JSON string version from #65.)

It's not clear how "Let policy-tokens be the result of parsing `Referrer-Policy` in response’s header list" works to me, but I guess it is probably delegating to some general HTTP header parsing thing defined in the HTTP spec. Probably whatever that is depends on the grammar in https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header, so that should stick around (again with potential modifications for #65).
