### ISSUE TITLE
Examples table

### ISSUE THREAD

**Issue by craigfrancis** [w3c/webappsec-referrer-policy#54]
Can the policy examples be converted to tables, so they confirm every scenario.

Originally suggested at: https://github.com/w3c/webappsec/issues/414

And please check the referrer values in these tables, I'm not sure they are correct (hence why I'd like to have examples).

---
## [no-referrer](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-no-referrer)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | NULL |
| https://example.com/page.html | **http**://example.com/ | NULL |
| https://example.com/page.html | https://example**.net**/ | NULL |
| https://example.com/page.html | **http**://example**.net**/ | NULL |
| **http**://example.com/page.html | https://example.com/ | NULL |
| **http**://example.com/page.html | **http**://example.com/ | NULL |
| **http**://example.com/page.html | https://example**.net**/ | NULL |
| **http**://example.com/page.html | **http**://example**.net**/ | NULL |
## [no-referrer-when-downgrade](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-no-referrer-when-downgrade)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | https://example.com/page.html |
| https://example.com/page.html | **http**://example.com/ | NULL |
| https://example.com/page.html | https://example**.net**/ | https://example.com/page.html ? |
| https://example.com/page.html | **http**://example**.net**/ | NULL |
| **http**://example.com/page.html | https://example.com/ | **http**://example.com/page.html ? |
| **http**://example.com/page.html | **http**://example.com/ | **http**://example.com/page.html ? |
| **http**://example.com/page.html | https://example**.net**/ | **http**://example.com/page.html ? |
| **http**://example.com/page.html | **http**://example**.net**/ | **http**://example.com/page.html ? |
## [same-origin](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-same-origin)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | https://example.com/page.html |
| https://example.com/page.html | **http**://example.com/ | https://example.com/page.html ? |
| https://example.com/page.html | https://example**.net**/ | NULL |
| https://example.com/page.html | **http**://example**.net**/ | NULL |
| **http**://example.com/page.html | https://example.com/ | **http**://example.com/page.html |
| **http**://example.com/page.html | **http**://example.com/ | **http**://example.com/page.html |
| **http**://example.com/page.html | https://example**.net**/ | NULL |
| **http**://example.com/page.html | **http**://example**.net**/ | NULL |
## [origin](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-origin)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | https://example.com/ |
| https://example.com/page.html | **http**://example.com/ | https://example.com/ |
| https://example.com/page.html | https://example**.net**/ | https://example.com/ |
| https://example.com/page.html | **http**://example**.net**/ | https://example.com/ |
| **http**://example.com/page.html | https://example.com/ | **http**://example.com/ |
| **http**://example.com/page.html | **http**://example.com/ | **http**://example.com/ |
| **http**://example.com/page.html | https://example**.net**/ | **http**://example.com/ |
| **http**://example.com/page.html | **http**://example**.net**/ | **http**://example.com/ |
## [origin-when-cross-origin](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-origin-when-cross-origin)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | https://example.com/page.html |
| https://example.com/page.html | **http**://example.com/ | https://example.com/ ? |
| https://example.com/page.html | https://example**.net**/ | https://example.com/ |
| https://example.com/page.html | **http**://example**.net**/ | https://example.com/ |
| **http**://example.com/page.html | https://example.com/ | **http**://example.com/ ? |
| **http**://example.com/page.html | **http**://example.com/ | **http**://example.com/page.html |
| **http**://example.com/page.html | https://example**.net**/ | **http**://example.com/ |
| **http**://example.com/page.html | **http**://example**.net**/ | **http**://example.com/ |
## [unsafe-url](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-unsafe-url)

| Source | Destination | Referrer |
| --- | --- | --- |
| https://example.com/page.html | https://example.com/ | https://example.com/page.html |
| https://example.com/page.html | **http**://example.com/ | https://example.com/page.html |
| https://example.com/page.html | https://example**.net**/ | https://example.com/page.html |
| https://example.com/page.html | **http**://example**.net**/ | https://example.com/page.html |
| **http**://example.com/page.html | https://example.com/ | **http**://example.com/page.html |
| **http**://example.com/page.html | **http**://example.com/ | **http**://example.com/page.html |
| **http**://example.com/page.html | https://example**.net**/ | **http**://example.com/page.html |
| **http**://example.com/page.html | **http**://example**.net**/ | **http**://example.com/page.html |

**Comment by estark37** [comment]
I think a full table showing every possible situation would be too verbose in the spec. The individual policies have examples inline. If there are specific cases that are confusing, I think we should add them as more such examples.

**Comment by craigfrancis** [comment]
I find the descriptions and current examples difficult to skim read (you need to spend a few minutes on each trying to understand what each one does).

I was hoping that each policy could have their own example table to show the 8 different combinations (rather than a single table for all policies, which would be too verbose)... I'd argue that these could even replace the current examples, which typically only focus on one or two scenarios.

e.g. most examples don't explain what happens when going from HTTP to HTTPS.
