### ISSUE TITLE
Update web-platform-tests

### ISSUE THREAD

**Issue by estark37** [w3c/webappsec-referrer-policy#57]
web-platform-tests needs to be updated for:
- [x] The Referrer-Policy header, and the removal of the CSP 'referrer' directive. (Already done in https://github.com/w3c/web-platform-tests/pull/3118!)
- [x] Remove tests for the old CSP 'referrer' directive
- [x] The new policy states same-origin, strict-origin, and strict-origin-when-cross-origin (#50)
- [x] Need test coverage for iframe srcdoc behavior

**Comment by jdm** [comment]
Tests for the Referrer-Policy header were added in https://github.com/w3c/web-platform-tests/pull/3118.

**Comment by estark37** [comment]
Thanks @jdm, I just noticed that myself yesterday. That's great! I think what we actually need to do then is remove the CSP delivery method from the tests, because the CSP directive is no longer in the spec.

**Comment by annevk** [comment]
We should probably at least keep one test to make sure the directive is not supported (change the pass condition).

**Comment by estark37** [comment]
@annevk sounds good, I'll make sure to leave one in.

**Comment by estark37** [comment]
I think the web-platform-test don't include tests for iframe srcdocs (whose behavior is being tweaked in https://github.com/whatwg/html/pull/1559); I just added that to the checklist. (cc @domenic)

**Comment by jdm** [comment]
See https://github.com/w3c/web-platform-tests/pull/2851 which requires updating.

**Comment by estark37** [comment]
Oh, thanks @jdm, I never saw that PR. I'll take a look and see if we can update it to reflect the new behavior, assuming https://github.com/whatwg/html/pull/1559 gets merged.

**Comment by fmarier** [comment]
Noting that the tests for [same-origin](https://github.com/w3c/web-platform-tests/pull/3153) and [strict-origin*](https://github.com/w3c/web-platform-tests/pull/3437) have been added.
