### ISSUE TITLE
Fetch integration is incorrect

### ISSUE THREAD

**Issue by jdm** [w3c/webappsec-referrer-policy#59]
[Http-redirect fetch](https://fetch.spec.whatwg.org/#http-redirect-fetch) no longer has a step 15, and doesn't directly invoke anything from this specification.

**Comment by estark37** [comment]
Hmm, thanks. I suppose that should be immediately before step 13. TBH I don't remember if we ever got Fetch updated to actually invoke this algorithm. I'll file an issue and a PR against Fetch for that in addition to fixing this section.
