### ISSUE TITLE
Consider using a dedicated header instead of CSP for referrer policy delivery

### ISSUE THREAD

**Issue by jeisinger** [w3c/webappsec-referrer-policy#6]
@mikewest @estark37

**Comment by mikewest** [comment]
@briansmith's suggestions in https://lists.w3.org/Archives/Public/public-webappsec/2015Oct/0048.html make sense to me, at least as far as the grammar goes:

    Referrer-Policy: [policy] [options]; [policy] [options]

I'm not sure that y'all want to implement the origin-based policy suggestion at the moment, but leaving room for it in the grammar sounds totally reasonable.

**Comment by estark37** [comment]
Fixed in https://github.com/w3c/webappsec-referrer-policy/pull/14
