### ISSUE TITLE
Take over "referrer policy" concept and ReferrerPolicy enum from Fetch

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-referrer-policy#62]
The setup I created to support referrer policies in the `fetch()` API makes introducing new values rather complicated as three specifications have to be updated.

If Referrer Policy includes https://fetch.spec.whatwg.org/#referrer-policies Fetch could just refer to Referrer Policy for that. Maybe HTML could do a similar thing, with HTML defining the attribute and Referrer Policy the value space.

**Comment by annevk** [comment]
@domenic might be interested in this too.

**Comment by estark37** [comment]
That seems like a good plan. How should I go about making this change? Copy that https://fetch.spec.whatwg.org/#referrer-policies into Referrer Policy first, then go update references in Fetch and HTML?

**Comment by domenic** [comment]
I can prioritize updating HTML for you, as I also want to solve https://github.com/whatwg/html/issues/1656

**Comment by annevk** [comment]
@estark37 I can update Fetch once the copy is done and review the copying change to Referrer Policy. No need for you to do all of it.

**Comment by annevk** [comment]
Fetch is updated too now.

**Comment by annevk** [comment]
Thanks everyone!
