### ISSUE TITLE
`Referrer-Policy` header syntax is incompatible with JSON.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-referrer-policy#65]
In the conversation on https://github.com/w3c/webappsec-referrer-policy/pull/14, it seemed like there was agreement (or at least, no objection) to the notion of retaining forward-compatibility with a more robust structure based on JSON. The current syntax doesn't. Was that an intentional decision?

That is, `Referrer-Policy: bareword` would make a JSON parser sad, whereas `Referrer-Policy: "quoted-keyword"` would not. I think the quoted version makes more sense, given the direction we seem to be going with header parsing. WDYT, @estark37?

/cc @fmarier @annevk

**Comment by estark37** [comment]
Wow, that whole part of the conversation seems to have completely dropped off my radar. Don't know what happened there but thanks for reminding me about it! I agree we should do this.

I'll put a PR together. (And we'll have to update the WPT and Chrome's implementation too.)

**Comment by annevk** [comment]
Firefox implements this header according to @franziskuskiefer and it'll hit stable in Firefox 50 (two releases from now it seems). Not sure if we still have room to change this around.

**Comment by mikewest** [comment]
If no one's using the current syntax (and I don't see how they could be using it, since no one is shipping it yet), then it seems like there's wiggle room. It might be more or less _comfortable_ depending on how close vendors are to shipping, but until there's real usage, it seems worth the mild discomfort to make the new syntax forward-compatible with a more structured encoding in the future.

**Comment by dveditz** [comment]
Is there any other HTTP header that has quoted values? Developers are going to leave off the quotes out of habit if nothing else leading to lots of broken policies or else implementations being "helpful" and interpreting them both ways.

The spec will have to be clear what happens then. An error and no restriction (default behavior) on referrer? An error and then fallback to the safe-and-hopefully-noticed no referrer at all?

**Comment by estark37** [comment]
@dveditz I would say unquoted values should be ignored like any other invalid policy, maybe with a console warning. (Can't remember if Chrome already has a console message for invalid policies or not.)

Also this is kind of ugly, but if we don't change the values to be quoted now, it's conceivable that we could still introduce a JSON-based syntax later with something like `Referrer-Policy: custom; {...}`, where there's an unquoted keyword to indicate that a JSON policy follows. Or something.

**Comment by jeisinger** [comment]
we discussed this at the TPAC meeting today and concluded to stick with the bare words for now.

**Comment by jeisinger** [comment]
closing as per previous comment
