### ISSUE TITLE
`ping-from`?

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-referrer-policy#70]
@jeisinger suggested in https://codereview.chromium.org/2360753002 that `ping-from` doesn't need to consider the site's referrer policy. That seems strange to me, as it's basically the same data leaking in the same way.

**Comment by jeisinger** [comment]
See https://github.com/whatwg/html/pull/712 and https://github.com/w3c/webappsec/issues/469

**Comment by mikewest** [comment]
If the conclusion is "If it's same-origin, you're screwed anyway", then why support policies like `origin`/`strict-origin`?

**Comment by annevk** [comment]
Also, the latter of the two issues is still open, so I'm not sure we really made a decision.

The way I would justify `ping` attribute leakage is the same way I justify `crossorigin` attribute leakage; it's part of the feature.

If we decide here that referrer policy can affect the `ping` attribute, we should probably also let it affect CORS. Or we should have some new set of principles that can explain that difference...

**Comment by jeisinger** [comment]
the conclusion was that if you're on http, you're screwed.

The other thing is that the page author put the ping attribute on the link. They could also just put referrerPolicy=unsafe-url on it. So I'd say sending the ping-from is what the author intended.

**Comment by mikewest** [comment]
Referrer policy should control `referer`, and `ping-from` is completely optional from the developer's perspective. WontFix.
