### ISSUE TITLE
redact location.ancestorOrigins according to Referrer Policy

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec-referrer-policy#71]
@bzbarsky @dakami and I had a hallway discussion at the end of TPAC about the possibility of adding location.ancestorOrigins to Firefox.  bz has had longstanding concerns about the information this leaks to iframes.  We arrived at a local consensus that any leakage is roughly equivalent to what happens already with referrer, so it would make sense to redact ancestorOrigins according to referrer policy.  (and this could resolve that objection to a Mozilla implementation of ancestorOrigins)

**Comment by wseltzer** [comment]
should this issue close along with #72?

**Comment by jeisinger** [comment]
Closing this issue in favor of the html one
