### ISSUE TITLE
noreferrer isn't integrated with <link>

### ISSUE THREAD

**Issue by jdm** [w3c/webappsec-referrer-policy#74]
https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery mentions using `noreferrer` on `<link>` elements. https://html.spec.whatwg.org/multipage/semantics.html#link-type-noreferrer does not mention this. Additionally, https://html.spec.whatwg.org/multipage/semantics.html#concept-link-obtain only refers to obtaining the policy from the element's `referrerpolicy` attribute.

**Comment by jeisinger** [comment]
hum, yeah, that looks like a typo in the referrer policy spec. @estark37 wdyt?

**Comment by mikewest** [comment]
`referrerpolicy` is now defined in https://html.spec.whatwg.org/#attr-link-referrerpolicy.

**Comment by domenic** [comment]
This should be reopened. It's about noreferrer, not referrerpolicy.

HTML does not define noreferrer to work on `<link>` elements, but this spec says that it applies there. Presumably this spec should be fixed, but maybe browsers support noreferrer there and HTML should be fixed?

**Comment by jeisinger** [comment]
https://github.com/w3c/webappsec-referrer-policy/pull/117
