### ISSUE TITLE
Add an example for multiple Referrer-Policy headers

### ISSUE THREAD

**Issue by estark37** [w3c/webappsec-referrer-policy#81]
@marumari points out that the spec is a little confusing on how you can use the Referrer-Policy header to specify multiple policies. https://w3c.github.io/webappsec-referrer-policy/#unknown-policy-values could do with an example, showing that `Referrer-Policy: origin no-referrer` is not going to work but that `Referrer-Policy: origin, no-referrer` will.

**Comment by marumari** [comment]
I know that _technically_ it's all listed deep within the HTTP specification, but for the average user I think it's unlikely that they'll be able to figure it out from simply reading the specification.  It doesn't help that similar specifications (such as HSTS and CSP) separate their directives with either spaces or semicolons.

**Comment by justin-morgan** [comment]
+1, I've been banging my head against the wall on this for a while, and finally found the definition way down in the RFC (https://tools.ietf.org/html/rfc2616#section-4.2).  There is already an example section for unknown policy values, so it would be relatively easy to add an explicit HTTP response header implementation to match the example text.

**Comment by annevk** [comment]
Probably good to have tests as well for edge cases such as:
```
Referrer-Policy: origin
Referrer-Policy: origin no-referrer
```
