### ISSUE TITLE
"TLS-protected" link seems not very useful

### ISSUE THREAD

**Issue by Ms2ger** [w3c/webappsec-referrer-policy#82]
It is used as a property of environment settings objects, but it links to some weird UI guidelines spec that talks about HTTP transactions.

**Comment by Ms2ger** [comment]
I expect we will need to do this check in the script thread before starting the fetch.

**Comment by mikewest** [comment]
@estark37 will take care of this

**Comment by mikewest** [comment]
We should change this to refer to having an HTTP state of "modern".
