### ISSUE TITLE
The CSS declaration block bit in the draft doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-referrer-policy#89]
I finally got a chance to read over the things from https://github.com/w3c/webappsec-referrer-policy/pull/83

This bit:

> If a CSS declaration block is responsible for the request

is wrong.  Consider this stylesheet:

    div { background: url(foo); }

That's a declaration block, and it's responsible for the request.  But that's not what the spec means by "declaration block".  It wants to restrict this case to inline style.  What you probably want to do is examine the .parentRule of the declaration block or something.

**Comment by jeisinger** [comment]
What about just making this the last step - any remaining case of declaration block should be an inline style ..

**Comment by bzbarsky** [comment]
What about presentation attributes, which get mapped into CSS styles but are not really associated with either stylesheets or declaration blocks?  Or maybe they are; Gecko creates declaration blocks for SVG presentation attributes and SMIL-animated stuff (but not HTML presentation attributes).

**Comment by jeisinger** [comment]
I created a PR here: https://github.com/w3c/webappsec-referrer-policy/pull/92 - wdyt?

**Comment by jeisinger** [comment]
actually, not sure why we need to restrict this to inline styles.

In the end, if the request doesn't come from a stylesheet, it comes from some declaration block, and if that block doesn't have an owner node, there's not much we can do.

But if it has one, why not use the referrer information from that node?

**Comment by bzbarsky** [comment]
> In the end, if the request doesn't come from a stylesheet, it comes from some declaration block

This is not necessarily true.  See above about presentation attributes...

**Comment by jeisinger** [comment]
if I'm reading the spec correctly, e.g., https://html.spec.whatwg.org/#the-page:attr-background says that the corresponding style property should be set, which would put it into an declaration block, no?

What about just adding a forth case: Otherwise: set the referrer policy to "never"

**Comment by bzbarsky** [comment]
> says that the corresponding style property should be set

It's used as a specified value in the cascade, is what it says.

> which would put it into an declaration block

No, because a declaration block is a CSSOM concept.  There is no declaration block associated with mapped attributes, necessarily.  One _could_ implement them in terms of one internally, of course, but nothing anywhere requires that.

The right way to solve this, in general, is for CSS to actually define a processing model for URIs that captures the right referrer information.  That is, any specified url() value would include not just the URL string but also the relevant referrer and referrer policy.  That's what UAs have to do in practice to implement this, no?

If the CSS working group is not cooperating in doing this, then you probably need to explicitly define how this works for the various sources of specified value information.  Those include stylesheets, inline styles, and presentation attributes.  I _think_ that's it (in the sense that the various SVG/SMIL stuff comes down to being presentation attributes and I'm pretty sure the SMIL source and target have to have the same referrer and referrer policy so you don't have to worry about them being mismatched... I think).

**Comment by jeisinger** [comment]
I don't think having url() specify the referrer is desirable.

Since we're already in the business of defining CSS for CSS, I could just require that every CSS declaration used in HTML & SVG that is not part of a stylesheet is part of a CSS declaration block that in turn has an owner node

**Comment by bzbarsky** [comment]
> I don't think having url() specify the referrer is desirable.

I'm not saying that there would be a refferrer string in the url() syntactic construct.

I'm saying that the url() syntactic construct would lead to the creation of a thing that, in addition to the url string, contains the information needed to load it properly (i.e. referrer and referrer policy, or something they can be gotten from).

> I could just require that every CSS declaration used in HTML & SVG that is not part of a stylesheet

Mapped attributes don't necessarily correspond to declarations either.  They really do just correspond to a specified value.

_Have_ you talked to the CSSWG about this stuff?

**Comment by jeisinger** [comment]
I did (last time at TPAC) but without success :/ 
Let me try to ask them more specific questions

**Comment by annevk** [comment]
@jeisinger let me state here what I suggested on IRC. File an issue at https://github.com/w3c/csswg-drafts/issues/new and link it with this one. Then, if we don't hear back, we can start pinging some individuals (or we can do that right away).
