### ISSUE TITLE
Where does a "block" come from in the sheet-with-null-location case?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec-referrer-policy#90]
Still reviewing https://github.com/w3c/webappsec-referrer-policy/pull/83

The new text says:

>  Otherwise, a CSS style sheet with a null location is responsible for the request: set the referrer to its owner node’s node document’s URL, and the referrer policy to the block’s owner node’s node document’s referrer policy. 

What is "the block" here?

**Comment by jeisinger** [comment]
that's a typo, thx for reporting!
