### ISSUE TITLE
Add referrer policy `origin-when-downgrade`

### ISSUE THREAD

**Issue by pulzarraider** [w3c/webappsec-referrer-policy#94]
I think there is a gap in the specification.

The browser's default is `no-referrer-when-downgrade`. 
After moving to `https` I found that this default policy kills referrer of our partner's sites that were still on http protocol. So I have changed the policy to `origin-when-cross-origin`. This works ok, because the partner sites on http gets the origin referrer.

But unfortunately this option sends origin referrer even to https pages, too. This has serious consequences for functionality of some pages on different origin (domain), that are relying on the full referrer.

In the specification is missing option, which allows sending the full referrer to https cross origin sites (like the `no-referrer-when-downgrade` does) and sends origin referrer to http sites (for security reasons).
The name  of this policy can be `origin-when-downgrade`.

**Comment by estark37** [comment]
Thanks for bringing this up! I was wondering if you could give a little more detail about the use case -- what's the functionality on cross-origin HTTPS pages that breaks if you send only the origin in the Referer header?

**Comment by pulzarraider** [comment]
My use case: in our company we are using advertising system that is on different origin (domain) and it is accessible on https. I am not developing this system, so I can't modify it's javascript code.

It uses referrer url to identify the page from which comes the request to display the ad. It sends advertising based on the referrer url. If it gets just the origin referrer it cannot do it`s job.

With browser`s default settings `no-referrer-when-downgrade` everything works ok, but after we started to use the `Referrer-Policy` header with other options that sends the origin referrer to unsecure pages, the ad system stopped working correctly.

We were forced to use the `unsafe-url` option, because we wanted to keep the ad system working as before and also don't kill the referrer for http partners. Unfortunately we are now sending full referrer to unsecured pages, which is not what we want. Unsecure pages should receive only the origin.

New option `origin-when-downgrade` which will send full referrer to secured cross-origin pages and just the origin referrer to unsecure pages will cover this use case and brings our users higher security.

**Comment by estark37** [comment]
@pulzarraider do you load the advertising system in an `iframe`? If so, can you use the `referrerpolicy` attribute to set a policy of `no-referrer-when-downgrade` for the advertising subresource load specifically? e.g.:

```
<meta name="referrer" content="origin">
...
<!-- Following this link will send the origin as the referrer. -->
<a href="http://nonsecure-partner.com">Click me</a>
...
<!-- iframe.html will be requested with the document's full URL as the referrer. -->
<iframe src="https://advertising-partner.com/iframe.html" referrerpolicy="no-referrer-when-downgrade"></iframe>
```

**Comment by pulzarraider** [comment]
@estark37 thank you for your tip, but the advertising system is not in iframe. It places ad images directly into `div` with specific `id` on the page.

**Comment by estark37** [comment]
Is the advertising system loaded in a script then? Can you use the `referrerpolicy` attribute on the script?

Or does the image resource request itself check the referrer?

**Comment by estark37** [comment]
It's been brought to my attention in https://github.com/w3c/webappsec-referrer-policy/issues/96 that there actually isn't a `referrerpolicy` attribute on `script` tags; I thought there was.

@jeisinger points out in https://github.com/w3c/webappsec-referrer-policy/issues/15#issuecomment-169622222 that you can always use a ServiceWorker to modify the referrer on specific resource requests.

(We might still want to add a `referrerpolicy` attribute on `script` -- I'd rather do that than add a new policy value, since I don't think we can reasonably add a new policy value for every possible policy that someone might want.)

**Comment by pulzarraider** [comment]
@estark37 Yes, it's loaded in a script. Thank you for the note about `ServiceWorker`, maybe we will try it.
Attribute on script will be much better and it will probably solve this issue.

**Comment by pulzarraider** [comment]
@estark37 why is this issue closed? Is the `referrerpolicy` attribute on `script` tag added in the scpecification?

**Comment by annevk** [comment]
@pulzarraider that's #96.
