### ISSUE TITLE
what should the referer header be for a fetch() from a blob: URL worker script?

### ISSUE THREAD

**Issue by wanderview** [w3c/webappsec-referrer-policy#95]
The fetch spec calls into:

https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer

Which states for workers that:

```
Otherwise, let referrerSource be environment’s creation URL. 
```

This suggests that the referer header should contains a `blob:` URL for fetch/xhr requests from a blob: URL worker script.

Is this intended?  What should the referer be in the case of a blob: URL worker script?

**Comment by wanderview** [comment]
Of course, a blob: URL in the referer header does not seem very useful.

**Comment by annevk** [comment]
It seems you can also get it for the `Window` object case due to only checking for opaque origins. I guess what we want instead is to restrict `Referer` values to HTTP(S) URLs?

**Comment by mikewest** [comment]
We do restrict the referrer value in step 2 of https://w3c.github.io/webappsec-referrer-policy/#strip-url (which is called from step ~4 of https://w3c.github.io/webappsec-referrer-policy/#determine-requests-referrer) by dropping it entirely in the case of "local" schemes. It looks like that's what Chrome does.

I'm not sure that totally makes sense, though; it might be reasonable for `blob:` URLs to fall back to the blob's origin? Or its base URL (do we screw with the base URL for blobby documents? How _do_ relative URLs work inside blobs?)? Perhaps @jeisinger or @estark37 have opinions?

**Comment by jeisinger** [comment]
we treat them as same origin with their creating document, right? seems like unwrapping the underlying origin and using that as referrer makes sense

**Comment by mikewest** [comment]
Right. That's what I was thinking too. Go make it happen. ;)

**Comment by annevk** [comment]
Making a URL out of an origin seems a little ugly. Note also that in that case you'd need to add a `/` and also account for it being an opaque origin.

**Comment by jeisinger** [comment]
we already do that if we restrict the referrer to an origin...

**Comment by annevk** [comment]
I thought we'd simply manipulate the URL, but I guess you can do that too...

**Comment by wanderview** [comment]
> we treat them as same origin with their creating document, right? seems like unwrapping the underlying origin and using that as referrer makes sense

Same as the document origin or the document creationURL?

I think gecko has a bug currently where we expose the document creationURL for the referer on fetches from a blob worker.

Personally, I liked the current spec'd behavior of just not sending a referer for local URLs.

**Comment by jeisinger** [comment]
I'd say same as the origin, I'd be fine with not sending an referrer header either

**Comment by jeisinger** [comment]
ok, closing this, as the spec covers the behavior, and the behavior seems right.

**Comment by kkaefer** [comment]
@annevk as per our discussion today, it looks like this _is_ defined correctly in the spec.
